### ISSUE TITLE
Lurker Crashes after poe startup

### ISSUE THREAD

**Issue by Motobell** [C1rdec/Poe-Lurker#139]
**Describe the bug**
Lurker worked up until a few weeks ago, then started crashing after poe startup.
I always started lurker by right clicking exe and running as admin before.
I followed advice from previous users who had a similar experience by 
Setup:

    Start setup.exe
    Go to %userprofile%\AppData\Local\PoeLurker
    Go to properties in the PoeLurker.exe
    Set administrator rights in comparability
This had the same effect od crashing.

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Version [e.g. v1.3.0] App- 1.5.26
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)
[2020/05/15 08:05:48.769] Error [1] Access is denied
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at Winook.Helper.Is64BitProcess(Process process)
   at Winook.HookBase.Install()
   at Lurker.MouseLurker..ctor(Process process, SettingsService settingsService)
   at Lurker.UI.ShellViewModel.<>c__DisplayClass58_0.<ShowOverlays>b__0()
   at Caliburn.Micro.XamlPlatformProvider.OnUIThread(Action action)
   at Lurker.UI.ShellViewModel.ShowOverlays(Process parentProcess)
   at Lurker.UI.ShellViewModel.<WaitForPoe>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Lurker.UI.App.Main() (Lurker.UI.AppBootstrapper)

**Additional context**
I run latest net framwork
windows 10

**Comment by C1rdec** [comment]
Yeah a fix is done in dev I'll publish it in an hour or so.

**Comment by Motobell** [comment]
Nice to hear that. I am missing the Lurker. Great work.

**Comment by C1rdec** [comment]
1.5.27 should fix your issue keep me updated :)

**Comment by Motobell** [comment]
That did it thank you!
