### ISSUE TITLE
Poe-lurker crashes when I change any settings. 

### ISSUE THREAD

**Issue by Cosmao** [C1rdec/Poe-Lurker#247]
As soon as I change anything in settings and press save the client crashes. Works with every option as soon as I press save. Running as administrator changes nothing. I've tried uninstalling the program and deleting everything in C:\Users\***\AppData\Local\PoeLurker and getting the latest version 1.8.8.

The settings seem to save since the debug mode will activate/deactivate if I try to change it and then restart.

I have .NET Framework 4.8.04084 installed.

[2021/02/19 16:45:51.087] Error [55] The calling thread cannot access this object because a different thread owns it.
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Window.Close()
   at Caliburn.Micro.WindowManager.WindowConductor.Deactivated(Object sender, DeactivationEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Caliburn.Micro.Screen.Caliburn.Micro.IDeactivate.Deactivate(Boolean close)
   at Caliburn.Micro.Conductor`1.Collection.AllActive.CloseItemCore(T item)
   at Caliburn.Micro.Conductor`1.Collection.AllActive.<>c__DisplayClass11_0.<DeactivateItem>b__0(Boolean canClose, IEnumerable`1 closable)
   at Caliburn.Micro.DefaultCloseStrategy`1.Evaluate(EvaluationState state, IEnumerator`1 enumerator, Action`2 callback)
   at Caliburn.Micro.DefaultCloseStrategy`1.Execute(IEnumerable`1 toClose, Action`2 callback)
   at Caliburn.Micro.Conductor`1.Collection.AllActive.DeactivateItem(T item, Boolean close)
   at Lurker.UI.ShellViewModel.DeactivateItem(Screen item, Boolean close)
   at Lurker.UI.ShellViewModel.<SettingsService_OnSave>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() (Lurker.UI.AppBootstrapper)

**Comment by C1rdec** [comment]
Can we connect on discord? 
That would help me to investigate.

**Comment by Cosmao** [comment]
Cosmo#1069 on discord.

I tried uninstalling, deleting the folder in appdata/local/PoeLuker and Appdata/roaming/PoeLuker and now I'm getting a new crash log but it behaves in the exact same way.

[2021/02/22 13:28:28.311] Error [13] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Lurker.UI.ShellViewModel.DeactivateItem(Screen item, Boolean close)
   at Lurker.UI.ShellViewModel.<SettingsService_OnSave>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() (Lurker.UI.AppBootstrapper)

**Comment by C1rdec** [comment]
Any updates?
