### ISSUE TITLE
Poe-Lurker closing unexpectedly - Invalid window handler.

### ISSUE THREAD

**Issue by bosmak** [C1rdec/Poe-Lurker#428]
**Describe the bug**
After opening PoE Lurker it quits unexpectedly

**To Reproduce**
1. Open PoE Lurker

**Expected behavior**
PoE Lurker doesn't quit.

**Screenshots**

**Please complete the following information:**
 - Version `1.24.0`
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)
```
[2024/08/07 16:32:45.002] Error [1] Invalid window handle
System.ComponentModel.Win32Exception (0x80004005): Invalid window handle
   at MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
   at System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Lurker.UI.App.Main() (Lurker.UI.AppBootstrapper)
[2024/08/07 19:29:23.805] Error [1] Invalid window handle
System.ComponentModel.Win32Exception (0x80004005): Invalid window handle
   at MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
   at System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Lurker.UI.App.Main() (Lurker.UI.AppBootstrapper)
```

**Additional context**
I use an ahk script to resize my PoE screen, I have been using it for the last two leagues and didn't have this problem.

**Comment by C1rdec** [comment]
The issue is related to a third party programs on your machine. Try to isolate the problem by running Poe Lurker without any other programs running.
