### ISSUE TITLE
Lurker started crashing randomly this league

### ISSUE THREAD

**Issue by Fiig86** [C1rdec/Poe-Lurker#431]
**Describe the bug**
Randomly stops working/crashes, when mouse over taskbar icon to check if program is open, icon disapears

**To Reproduce**
1. Open program
2. play game for a bit
3. bottom left hideout button disappears,trade buttons do not appear, taskbar icon disappears

**Expected behavior**
program works until manually closed like previously

**Screenshots**

**Please complete the following information:**
 - Version 1.24
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)
 -
[2024/08/16 00:36:23.423] Error [1] UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) (Lurker.UI.AppBootstrapper)

**Additional context**
I had no issues before this league 3.25
I've tried to uninstall and reinstalling POE Lurker
Only thing i've done is install RTSS for afterburner but disabled it after this started to happen, but it did not have any affect

**Comment by C1rdec** [comment]
This is related to an issue with a third party software on your computer
