### ISSUE TITLE
Log Submit

### ISSUE THREAD

**Issue by mhasanbulli** [C1rdec/Poe-Lurker#61]
Hello,

Is there anyway to submit logs for crashes? The app crashes from time to time but I cannot seem to reproduce when and/or under what conditions. 

By the way, this is such a cool app.

**Comment by C1rdec** [comment]
Yeah for now you'll need to navigate to the exe location.

C:\Users\[user]\AppData\Local\PoeLurker\app-version\logs

**Comment by mhasanbulli** [comment]
Oh cool.

Would you like to receive logs? I am not sure if you are collecting them. It might be helpful to iron out some of the small issues :)

**Comment by C1rdec** [comment]
Paste the last error here

**Comment by C1rdec** [comment]
But yeah I'm currently working on an Azure Function so I can get all the errors

**Comment by C1rdec** [comment]
Do you have the log?

**Comment by mhasanbulli** [comment]
I will compile them when I get home from work today. I was trying to record other cases as well.

**Comment by mhasanbulli** [comment]
I cannot see lines with ERR but there are bunch of WARN lines and they seem to match when the app quits, or although it is running it does not respond. Here is an example of such event log.

```
[2020/02/05 20:03:10.426] Trace [51] Not parsed: 2020/02/05 20:03:10 303828906 159 [WARN Client 10716] Matching object found for InstanceClientActionUpdate, but no matching action was found on object to update. (Lurker.ClientLurker)
[2020/02/05 20:03:23.485] Trace [47] Not parsed: 2020/02/05 20:03:23 303841875 159 [WARN Client 10716] Matching object found for InstanceClientActionUpdate, but no matching action was found on object to update. (Lurker.ClientLurker)
[2020/02/05 20:04:31.273] Trace [48] Not parsed: 2020/02/05 20:04:30 303909562 159 [WARN Client 10716] Matching object found for InstanceClientActionUpdate, but no matching action was found on object to update. (Lurker.ClientLurker)
[2020/02/05 20:05:56.620] Trace [48] Not parsed: flags: 129 (Lurker.ClientLurker)
[2020/02/05 20:05:56.630] Trace [48] Not parsed: target_id: 460 (Lurker.ClientLurker)
[2020/02/05 20:05:56.637] Trace [48] Not parsed: object_id: 779 (Lurker.ClientLurker)
[2020/02/05 20:05:56.637] Trace [48] Not parsed: action_id: 35887 (Lurker.ClientLurker)
[2020/02/05 20:05:56.658] Trace [48] Not parsed: skill_instance_id: 34819 (Lurker.ClientLurker)
[2020/02/05 20:05:56.658] Trace [48] Not parsed: 2020/02/05 20:05:56 303995093 1e3 [WARN Client 10716] Instant/Triggered actionwas serialized to the client, but the client failed to execute the action. (Lurker.ClientLurker)
[2020/02/05 20:05:56.671] Trace [48] Not parsed: 2020/02/05 20:05:56 303995093 262 [WARN Client 10716] Client couldn't execute an instant/triggered action from the server (Lurker.ClientLurker)
[2020/02/05 20:06:08.713] Trace [54] Not parsed: 2020/02/05 20:06:08 304007453 159 [WARN Client 10716] Matching object found for InstanceClientActionUpdate, but no matching action was found on object to update. (Lurker.ClientLurker)
```
I can attach the logs if you like. Just let me know :)

**Comment by C1rdec** [comment]
Yes those are lines from poe

**Comment by mhasanbulli** [comment]
Here is the latest error.
```
[2020/02/09 15:21:05.938] Error [23] Input string was not in a correct format.
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at Lurker.Events.TradeEvent.ParseLocation(String locationValue)
   at Lurker.Events.TradeEvent..ctor(String logLine)
   at Lurker.Events.TradeEvent.TryParse(String logLine)
   at Lurker.ClientLurker.OnFileChanged(String newline)
   at Lurker.ClientLurker.<LurkLastLine>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() (Lurker.UI.AppBootstrapper)
```

**Comment by C1rdec** [comment]
Pretty sure that 1.3.1 fixed this issue

**Comment by mhasanbulli** [comment]
Yeah. I am pretty sure I am using the latest. However, I can uninstall and re-install it when I get home from work today.

**Comment by C1rdec** [comment]
Can you provide the log file of POE `Client.txt` 

Path of Exile Folder\logs\client.txt

**Comment by mhasanbulli** [comment]
Here is a Google Drive link https://drive.google.com/file/d/1T4m1MB2nUsavlkmrJSoTvllWdnlPM03Y/view?usp=sharing

**Comment by C1rdec** [comment]
Found the faulty line :P 

`2020/02/09 15:21:05 164631375 ac9 [INFO Client 14116] @From <zøkÏng> ㄹㅏ잔: Hi, I would like to buy your Bottled Faith Sulphur Flask listed for 15 exa in Metamorph (stash tab "Market"; position: left 12, top 10) / / /CAN SELL ME TO 14EX ท`

Will be fiex in 1.3.2
