### ISSUE TITLE
[BUG] Improper parsing of location from poe.app

### ISSUE THREAD

**Issue by tamaroth** [C1rdec/Poe-Lurker#65]
**Describe the bug**
When an incoming message is formatted in an unexpected way, Lurker fails to parse it an crashes instead.

**To Reproduce**
1. Launch Lurker
2. In PoE, send yourself the following message: `wtb Fire and Ice listed for 5 Chaos Orb in Metamorph(stash "~price 5 chaos"; left 1, top 12)`.

**Expected behavior**
Not crashing.

**Please complete the following information:**
 - Version [e.g. v1.3.0]
 - Provide Log (C:\Users\[user]\AppData\Local\PoeLurker\app-[version]\logs)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Lurker.Items.Extensions.StringExtension.Split(String value, String splitValue)
   at Lurker.Events.TradeEvent.ParseLocation(String locationValue)
   at Lurker.Events.TradeEvent..ctor(String logLine)
   at Lurker.Events.TradeEvent.TryParse(String logLine)
   at Lurker.ClientLurker.OnFileChanged(String newline)
   at Lurker.ClientLurker.<LurkLastLine>d__48.MoveNext()
```

**Additional context**
I have tried to improve upon the currently existing parsing solution with the use of regular expression to help with the current bug and possibly reduce any future ones. The code is waiting for a review in #64

**Comment by C1rdec** [comment]
Fixed in 1.3.3
